curso_django/base/urls.py
from django.urls import path

from curso_django.base.views import home

app_name = 'base'
urlpatterns = [
    path('', home, name='home'),
]

curso_django/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('curso_django.base.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

curso_django/base/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given email, and password.
        """
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_staff', True)

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """
    App base User Class

    Email e password são obrigatórios o resto é opcional.
    """
    first_name = models.CharField(_('first name'), max_length=150, blank=True)
    email = models.EmailField(_('email address'), unique=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s' % self.first_name
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

curso_django/base/views.py
from django.shortcuts import render

# Create your views here.


def home(request):
    return render(request, 'base/home.html')

curso_django/base/templates/base/home.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Curso</title>
	<link rel="icon" type="image/png" href="{% static 'img/favicon.png'%}">

    <meta name="description" content="Source code generated using layoutit.com">
    <meta name="author" content="Rafael Fonseca">

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
  	<script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>

  </head>
  <body>

    <div class="container">
	<div class="row">
		<div class="col-md-12">
			<ul class="nav nav-tabs">
				<li class="nav-item">
					<a class="nav-link active" href="{% url 'base:home' %}">Curso</a>
				</li>
			</ul>
			<div class="jumbotron">
				<h2>
					Site desenvolvido no curso <a href="https://pythonpro.com.br/">Python Pro</a> de Renzo Nuccitelli,
					para aprender Django.
				</h2>
				<p>
					Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur nec augue in dolor hendrerit
					ultrices. Phasellus id viverra sem. Sed vitae rutrum enim, at consectetur purus. Ut pretium, nisi ac
					semper tristique, odio orci vulputate augue, non consequat nibh turpis ac ante. Maecenas imperdiet
					tincidunt sapien, sed elementum orci aliquam non. Duis efficitur lacinia purus. Lorem ipsum dolor
					sit amet, consectetur adipiscing elit. Sed vel massa tristique, mollis sapien et, laoreet nunc.
					Ut vitae magna a quam pellentesque fermentum. Aliquam pellentesque libero a libero venenatis,
					a venenatis ex tempor.
				</p>

			</div>
			<div class="row">
				<div class="col-md-12">
					<div class="card">
						<h5 class="card-header">
							Ferramentas utilizadas:
						</h5>
						<div class="card-body">
							<p class="card-text">

								<br><br>
								<a href="https://www.djangoproject.com/" target="_blank">
									<img src="{% static 'img/django-logo.png' %}" alt="Django" class="img-thumbnail mr-3 ml-3">
								</a>Framework gratuito e de código aberto que facilita a maior parte do desenvolvimento
								web.<br><br>

								<a href="https://getbootstrap.com/" target="_blank">
									<img src="{% static 'img/bootstrap-logo.png' %}" alt="Bootstrap" class="img-thumbnail mr-3 ml-3">
								</a>É um popular kit de ferramentas de front-end de código aberto.<br><br>

								<a href="https://www.postgresql.org/" target="_blank">
									<img src="{% static 'img/postgress-logo.png' %}" alt="Postgress" class="img-thumbnail mr-3 ml-3">
								</a>É um banco de dados relacional de código aberto.<br><br>

								<a href="https://sqlite.org/index.html" target="_blank">
									<img src="{% static 'img/sqlite-logo.png' %}" alt="Sqlite" class="img-thumbnail mr-3 ml-3">
								</a>É uma biblioteca em linguagem C que implementa um banco de dados SQL.<br><br>

								<a href="https://github.com/" target="_blank">
									<img src="{% static 'img/GitHub-logo.png' %}" alt="GitHub" class="img-thumbnail mr-3 ml-3">
								</a>Plataforma de desenvolvimento que ajuda a manter o versionamento do código.<br><br>

								<a href="https://travis-ci.com/" target="_blank">
									<img src="{% static 'img/travis-logo.png' %}" alt="Travis" class="img-thumbnail mr-3 ml-3">
								</a>Implementa a integração contínua.<br><br>

								<a href="https://pyup.io/" target="_blank">
									<img src="{% static 'img/py-up-logo.png' %}" alt="Py-Up" class="img-thumbnail mr-3 ml-3">
								</a>Ferramenta utilizada para gerir as dependências utilizadas.<br><br>

								<a href="https://docs.pytest.org/en/6.2.x/" target="_blank">
									<img src="{% static 'img/pytest-logo.png' %}" alt="Pytest" class="img-thumbnail mr-3 ml-3">
								</a>É uma ferramenta de teste da língua Python.<br><br>

								<a href="https://about.codecov.io/" target="_blank">
									<img src="{% static 'img/codecov-logo.png' %}" alt="Codecov" class="img-thumbnail mr-3 ml-3">
								</a>Ferramenta que auxilia a manter a cobertura do código.<br><br>

								<a href="https://www.heroku.com/" target="_blank">
									<img src="{% static 'img/heroku-logo.png' %}" alt="Heroku" class="img-thumbnail mr-3 ml-3">
								</a>É uma plataforma como serviço (PaaS) que permite disponibilizar o site na internet.
								<br><br>

								<a href="https://aws.amazon.com/pt/" target="_blank">
									<img src="{% static 'img/amazon-s3-logo.png' %}" alt="Amazon S3" class="img-thumbnail mr-3 ml-3">
								</a>O Amazon S3 é um serviço de armazenamento para a Internet.<br><br>

								<a href="https://sentry.io/" target="_blank">
									<img src="{% static 'img/sentry-logo.png' %}" alt="Sentry" class="img-thumbnail mr-3 ml-3">
								</a>Software que monitora erros e desempenho, no ambiente de produção.
								<br><br>

							</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	</div>

  	<footer class="main-footer mt-5 pt-4 text-white">
		<div class="container">
			<div class="row">
				<div class="col">
					<h3>Entre em contato</h3>
					<adress>
						+55 61 99554-2832
						<br>
						<a href="mailto:rafael.abreu.fonseca@gmail.com" class="text-white">rafael.abreu.fonseca@gmail.com</a>
					</adress>
				</div>
			</div>
		</div>

		<div class="rights pb-4">
			<div class="container">
				<div class="row">
					<div class="col">
						{%now 'Y'%} - Todos os direitos reservados
					</div>
				</div>
			</div>
		</div>
	</footer>
  </body>
</html>